
services:
  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: movie_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped

  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
